# What protocol to use when performing git operations. Supported values: ssh, https
git_protocol: https
# What editor gh should run when creating issues, pull requests, etc. If blank, will refer to environment.
editor:
# When to interactively prompt. This is a global config that cannot be overridden by hostname. Supported values: enabled, disabled
prompt: enabled
# A pager program to send command output to, e.g. "less". Set the value to "cat" to disable the pager.
pager:
# Aliases allow you to create nicknames for gh commands
aliases:
    aliases: alias list
    issues: issue list
    co: '!id="$(gh pr list -L100 | fzf --height 40% --reverse --exit-0 | cut -f1)"; [ -n "$id" ] && gh pr checkout "$id"'
    checkout: '!id="$(gh pr list -L100 | fzf --height 40% --reverse --exit-0 | cut -f1)"; [ -n "$id" ] && gh pr checkout "$id"'
    switch: '!id="$(gh pr list -L100 | fzf --height 40% --reverse --exit-0 | cut -f1)"; [ -n "$id" ] && gh pr checkout "$id"'
    prs: pr list
    open: repo view -w
    o: repo view -w
    b: repo view -w
