# File:   bash_profile
# Author: Shoichi Aizawa <shoichiaizawa@gmail.com>
# Source: https://github.com/shoichiaizawa/dotfiles/tree/master/bash/bash_profile

# This only runs on user login
echo ""
echo -n "Welcome to Unix on macOS, "; whoami
echo ""
echo -n "Today is "; date "+%Y-%m-%d %H:%M:%S %z"
echo ""
cal

# This loads in the configuration in .bashrc
# Put all configuration there!
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

# Source .bash.local, if present
if [ -f ~/.bashrc.local ]; then
  source ~/.bashrc.local
fi

if type neofetch > /dev/null 2>&1; then
  neofetch
elif [ -f ~/.bash/welcome.sh ]; then
  sh ~/.bash/welcome.sh
fi

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
