# File:   bash_profile
# Author: Shoichi Aizawa <shoichiaizawa@gmail.com>
# Source: https://github.com/shoichiaizawa/dotfiles/tree/master/bash/bash_profile

# This loads in the configuration in .bashrc
# Put all configuration there!
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

# Source .bash.local, if present
if [ -f ~/.bashrc.local ]; then
  source ~/.bashrc.local
fi

if type fastfetch > /dev/null 2>&1; then
  fastfetch
fi

test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"
